### ISSUE TITLE
Repository keywords

### ISSUE THREAD

**Issue by ivan-pi** [jacobwilliams/polyroots-fortran#1]
The following keywords (taken from NIST GAMS) may be appropriate: [Jenkins-Traub method](https://gams.nist.gov/cgi-bin/serve.cgi/ClassIndex?Key=%27Jenkins-Traub%20method%27), [Laguerre method](https://gams.nist.gov/cgi-bin/serve.cgi/ClassIndex?Key=%27Laguerre%20method%27), [Nonlinear equations](https://gams.nist.gov/cgi-bin/serve.cgi/ClassIndex?Key=%27Nonlinear%20equations%27), [Polynomial](https://gams.nist.gov/cgi-bin/serve.cgi/ClassIndex?Key=%27Polynomial%27), [Polynomial equations](https://gams.nist.gov/cgi-bin/serve.cgi/ClassIndex?Key=%27Polynomial%20equations%27)

[Searching for "Jenkins-Traub"](https://github.com/search?q=jenkins+traub) gives mostly variants of the original `RPOLY` routine in C++, Python, Javascript, Haskell, C, Ada, and C#.

Searching for "laguerre-method", I've found the following relevant results:
* [FPML](https://github.com/trcameron/FPML) (a newer library in Fortran by @trcameron; the author also provides [FPML-Comp](https://github.com/trcameron/FPML-Comp), a library for polishing the polynomial roots)
* [polynomial-solver](https://github.com/M-Salti/Polynomial-solver) (in C++) and [rootpolynomialfinder](https://github.com/prinewgirl-zz/rootpolynomialfinder) (in C) which implement Laguerre's method, but look more like homework projects

The other keywords provide much more broad and varied results related also to fitting, evaluation, and other types of polynomial equations I never knew existed...

**Comment by jacobwilliams** [comment]
done
