### ISSUE TITLE
Build fails on PPC due to missing ieee_arithmetic

### ISSUE THREAD

**Issue by barracuda156** [jacobwilliams/polyroots-fortran#20]
```
[  0%]           polyroots_module.F90
 + mkdir -p build/gfortran_EDF3F128DBFCA123/polyroots-fortran/
 + gfortran -c ././src/polyroots_module.F90  -O3 -funroll-loops -Wimplicit-interface -fPIC -fmax-errors=1 -fcoarray=single -J build/gfortran_EDF3F128DBFCA123 -Ibuild/gfortran_EDF3F128DBFCA123 -o build/gfortran_EDF3F128DBFCA123/polyroots-fortran/src_polyroots_module.F90.o
././src/polyroots_module.F90:24:8:

     use ieee_arithmetic
        1
Fatal Error: Can't open module file 'ieee_arithmetic.mod' for reading at (1): No such file or directory
compilation terminated.
[ 50%]           polyroots_module.F90  done.

././src/polyroots_module.F90:24:8:

     use ieee_arithmetic
        1
Fatal Error: Can't open module file 'ieee_arithmetic.mod' for reading at (1): No such file or directory
compilation terminated.
<ERROR> Compilation failed for object " src_polyroots_module.F90.o "
<ERROR>stopping due to failed compilation
```

**Comment by jacobwilliams** [comment]
`ieee_arithmetic` is from Fortran 2003, so I guess your compiler doesn't support it. You'll need a newer compiler to compile this library.

**Comment by barracuda156** [comment]
> `ieee_arithmetic` is from Fortran 2003, so I guess your compiler doesn't support it. You'll need a newer compiler to compile this library.

@jacobwilliams In is not a problem with compiler version, the latest GCC does not have it yet for Darwin PPC.

(Anyway, I got tired of these errors and wrote implementation two days ago. If tests pass, maybe GCC will get it finally.)

**Comment by barracuda156** [comment]
@jacobwilliams By the way, if you have some free time, maybe you could help with that? What was needed is to write a header complimenting system `fenv.h` and adding needed functions to manipulate FP. For PPC implementations are OS-based, and macOS cannot use glibc or AIX ones.
