### ISSUE TITLE
one of tests fails

### ISSUE THREAD

**Issue by msz59** [jacobwilliams/polyroots-fortran#9]
I do not use fpm so I have just compiled the module and the tests using Ubuntu 22.04 default gfortran v. 11.2.0 and liblapack3 (3.10.0) package (for "-llapack"). I used option "-O2" both for module and tests build.

The 'rpoly_test.f90' error-stops in CASE - 2 part of test, at cpqr79:

cpqr79
real part               imaginary part         root
no convergence in 30 qr iterations. ierr =            4
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
ERROR STOP  ** failure in cpqr79 **

**Comment by jacobwilliams** [comment]
Yes, you can see the same issue when you run with FPM:

```
fpm test --profile release
```

**Comment by jacobwilliams** [comment]
Should be fixed now!
